// Generated by CoffeeScript 1.9.0
(function() {
  var User, lastUserId;

  lastUserId = 0;

  User = (function() {
    function User(nick) {
      this.id = lastUserId++;
      this.nick = nick != null ? nick : User.defaultNick;
      this.loggedIn = false;
    }

    User.prototype.setNick = function(nick) {
      return this.nick = nick;
    };

    return User;

  })();

  User.defaultNick = "Anonymous";

  module.exports = User;

}).call(this);

//# sourceMappingURL=User.js.map
