// Generated by CoffeeScript 1.9.0
(function() {
  var app, config, express, http, indexCtrl, io, nconf;

  express = require('express');

  app = express();

  http = require('http').Server(app);

  io = require('socket.io')(http);

  nconf = require('nconf');

  config = nconf.file({
    file: 'config.json'
  });

  indexCtrl = require('./controllers/index.coffee');

  app.set('view engine', 'jade');

  app.set('views', __dirname + '/views');

  app.use(express["static"](__dirname + '/public'));

  app.get('/', function(req, res) {
    return indexCtrl.view(req, res);
  });

  io.on('connection', function(socket) {
    return console.log('a user connected');
  });

  http.listen(config.get('server:port'), function() {
    return console.log("listening on *:" + (config.get('server:port')));
  });

}).call(this);

//# sourceMappingURL=app.js.map
