// Generated by CoffeeScript 1.9.0
(function() {
  var User, app, config, express, http, id, indexCtrl, io, nconf, socketToUser, users;

  express = require('express');

  app = express();

  http = require('http').Server(app);

  io = require('socket.io')(http);

  nconf = require('nconf');

  config = nconf.file({
    file: 'config.json'
  });

  indexCtrl = require('./controllers/index.coffee');

  User = require('./models/User.coffee');

  app.set('view engine', 'jade');

  app.set('views', __dirname + '/views');

  app.use(express["static"](__dirname + '/public'));

  app.get('/', function(req, res) {
    return indexCtrl.view(req, res);
  });

  users = {};

  socketToUser = {};

  id = 0;

  io.on('connection', function(socket) {
    var user;
    console.log('a user connected');
    user = x({
      id: ++id,
      socket: socket,
      loggedIn: false
    });
    users[user.id] = user;
    socketToUser[socket.id] = user.id;
    return socket.on('disconnect', function() {
      delete users[user.id];
      delete socketToUser[socket.id];
      if (user.loggedIn) {
        return io.emit('user.leave', user.nick);
      }
    }).on('login', function(nick) {
      var data;
      if ((nick == null) || nick === '') {
        socket.emit('login.error', 'Недопустимый ник');
      }
      if (user) {
        return socket.emit('login.error', nick + " уже тут");
      } else {
        user.nick = nick;
        socketToUser[socket.id] = nick;
        socket.emit('login.ok');
        data = {
          nick: nick,
          users: Object.getOwnPropertyNames(users)
        };
        return io.emit('user.join', JSON.stringify(data));
      }
    }).on('changeNick', function(nick) {
      var data, oldNick;
      oldNick = socketToUser[socket.id];
      if (oldNick != null) {
        socketToUser[socket.id] = nick;
        users[nick] = socket;
        delete users[oldNick];
      } else {
        socketToUser[socket.id] = nick;
        users[nick] = socket;
      }
      data = {
        oldNick: oldNick,
        newNick: nick
      };
      return io.emit('user.changeNick', JSON.stringify(data));
    });
  });

  http.listen(config.get('server:port'), function() {
    return console.log("listening on *:" + (config.get('server:port')));
  });

}).call(this);

//# sourceMappingURL=app.js.map
