// Generated by CoffeeScript 1.9.0
(function() {
  var IndexController;

  IndexController = {
    view: function(req, res) {
      return res.render('index.jade', {
        pageTitle: 'Node Chat',
        desc: 'Welcome to the Node Chat'
      });
    }
  };

  module.exports = IndexController;

}).call(this);

//# sourceMappingURL=index.js.map
